/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#343535",
        "surface-bright": "#383939",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#dfc0af",
        "on-primary": "#313030",
        "on-tertiary": "#3f2c20",
        "inverse-primary": "#5f5e5e",
        "on-primary-container": "#7e7d7d",
        "surface-container": "#1e2020",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-surface": "#e3e2e2",
        "tertiary-fixed": "#fcdcca",
        "on-tertiary-container": "#927869",
        "secondary-fixed-dim": "#e9c176",
        "on-primary-fixed": "#1c1b1b",
        "surface-container-low": "#1a1c1c",
        "inverse-surface": "#e3e2e2",
        "surface-tint": "#c8c6c5",
        "on-secondary-fixed": "#261900",
        "primary-container": "#121212",
        "on-primary-fixed-variant": "#474646",
        "outline": "#8e9192",
        "surface-dim": "#121414",
        "primary-fixed": "#e5e2e1",
        "surface-container-lowest": "#0d0e0f",
        "surface-container-highest": "#343535",
        "on-surface-variant": "#c4c7c7",
        "primary-fixed-dim": "#c8c6c5",
        "surface": "#121414",
        "on-background": "#e3e2e2",
        "secondary-fixed": "#ffdea5",
        "on-secondary-container": "#dab36a",
        "primary": "#c8c6c5",
        "secondary-container": "#604403",
        "surface-container-high": "#292a2a",
        "tertiary": "#dfc0af",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#584235",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary-container": "#1d0e05",
        "background": "#121414",
        "secondary": "#e9c176",
        "outline-variant": "#444748",
        "on-secondary": "#412d00",
        "inverse-on-surface": "#2f3131",
        "on-tertiary-fixed": "#28180d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-tablet": "40px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "base": "8px",
        "container-max": "1280px",
        "margin-desktop": "80px"
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "label-md": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
